#include "bignum.h"
/*!
 * \brief count trailing zeros in byte x, asm version
 */
BYTE byte_ctz_avr(BYTE x)
{
    asm volatile(
            "mov __tmp_reg__, %A0    \n\t"
            "sbrc __tmp_reg__, 0     \n\t"
            "rjmp CTZL0              \n\t"
            "sbrc __tmp_reg__, 1     \n\t"
            "rjmp CTZL1              \n\t"
            "sbrc __tmp_reg__, 2     \n\t"
            "rjmp CTZL2              \n\t"
            "sbrc __tmp_reg__, 3     \n\t"
            "rjmp CTZL3              \n\t"
            "sbrc __tmp_reg__, 4     \n\t"
            "rjmp CTZL4              \n\t"
            "sbrc __tmp_reg__, 5     \n\t"
            "rjmp CTZL5              \n\t"
            "sbrc __tmp_reg__, 6     \n\t"
            "rjmp CTZL6              \n\t"
            "sbrc __tmp_reg__, 7     \n\t"
            "rjmp CTZL7              \n\t"
            "ldi %B0, 8              \n\t"
            "rjmp CTZDONE            \n\t"
            "CTZL0:                  \n\t"
            "ldi %B0, 0              \n\t"
            "rjmp CTZDONE            \n\t"
            "CTZL1:                  \n\t"
            "ldi %B0, 1              \n\t"
            "rjmp CTZDONE            \n\t"
            "CTZL2:                  \n\t"
            "ldi %B0, 2              \n\t"
            "rjmp CTZDONE            \n\t"
            "CTZL3:                  \n\t"
            "ldi %B0, 3              \n\t"
            "rjmp CTZDONE            \n\t"
            "CTZL4:                  \n\t"
            "ldi %B0, 4              \n\t"
            "rjmp CTZDONE            \n\t"
            "CTZL5:                  \n\t"
            "ldi %B0, 5              \n\t"
            "rjmp CTZDONE            \n\t"
            "CTZL6:                  \n\t"
            "ldi %B0, 6              \n\t"
            "rjmp CTZDONE            \n\t"
            "CTZL7:                  \n\t"
            "ldi %B0, 7              \n\t"
            "CTZDONE:                \n\t"
            "mov %A0, %B0            \n\t"
            : "+r" (x) );
    return x;
}
