/*
   Author: Yogesh Nagarkar
   Copyright: YesHog (www.yeshog.com)
*/
#define    OK                                            0xFFB4
#define    ERR_STATE                                     0xFFB3
/* rtl */
#define    RTL_DRV_INIT_FAILED                           0xFFA3
#define    RTL_DRV_OVERRUN                               0xFFA2
#define    RTL_NO_PKT                                    0xFFA1
#define    RTL_BNRY_SKEW                                 0xFFA0
#define    RTL_DRV_RX_FRAME_TOO_BIG                      0xFF9F
#define    RTL_DRV_OUT_OF_MEMORY                         0xFF9E
#define    RTL_DRV_REMOTE_DMA_HUNG                       0xFF9D
#define    RTL_DRV_TX_FRAME_TOO_BIG                      0xFF9C
#define    RTL_DRV_NULL_TX_PKT                           0xFF9B
#define    RTL_DRV_TX_REMOTE_DMA_HUNG                    0xFF9A
#define    RTL_DRV_TX_RUNT_PKT                           0xFF99
#define    RTL_NXT_PG_INVALID                            0xFF98
#define    RTL_DRV_RX_FRAME_TOO_SMALL                    0xFF97
#define    RTL_BROADCAST_BASTARD_PACKET                  0xFF96
#define    RTL_BROADCAST_IP_MAN                          0xFF95
/* l2 <=> ethernet */
#define    ETH_UNKNOWN_PAYLOAD                           0xFF85
#define    ETH_DST_ETH_NOT_ME                            0xFF84
#define    ETH_PKT_LEN_ZERO                              0xFF83
#define    ETH_PROCESS_RX_NULL_PKT                       0xFF82
/* arp */
#define    ARP_REPLY_NO_MEM                              0xFF72
#define    ARP_PKT_TOO_SMALL                             0xFF71
#define    ARP_PKT_SRC_MAC_UNTRUSTED                     0xFF70
#define    ARP_PKT_SRC_IP_UNTRUSTED                      0xFF6F
#define    ARP_PKT_SEND_RESPONSE                         0xFF6E
/* l3 <=> ip*/
#define    IP_HEADER_LEN_TOO_SMALL                       0xFF5E
#define    IP_HEADER_DATA_LEN_ZERO                       0xFF5D
#define    IP_HEADER_DST_NOT_ME                          0xFF5C
#define    IP_HEADER_DATA_LEN_TOO_BIG                    0xFF5B
#define    IP_HEADER_AND_ACTUAL_LEN_MISMATCH             0xFF5A
#define    IP_HEADER_LEN_BIGGER_THAN_PKT                 0xFF59
#define    IP_HEADER_PROTO_NOT_SUPPORTED                 0xFF58
/* l4 <=> tcp */
#define    TCP_HEADER_PKT_TOO_SMALL                      0xFF48
#define    TCP_HEADER_LEN_TOO_BIG                        0xFF47
#define    TCP_HEADER_DST_PORT_NOT_ME                    0xFF46
#define    TCP_HEADER_LEN_BIGGER_THAN_PKT                0xFF45
#define    TCP_HEADER_CHECKSUM_VERIFY_FAILED             0xFF44
#define    TCP_HEADER_SYN_WITH_DATA                      0xFF43
#define    TCP_CONN_SYN_RECD_BUT_BUSY                    0xFF42
#define    TCP_CONN_SYN_ACK_SND_ERR                      0xFF41
#define    TCP_CONN_ACK_NUM_MISMATCH                     0xFF40
#define    TCP_UNKNOWN_ST                                0xFF3F
#define    TCP_CONN_DUP_PKT                              0xFF3E
#define    TCP_CONN_ACK_NUM_OVERFLOW                     0xFF3D
#define    TCP_CONN_FLOW_ST_MISMATCH                     0xFF3C
#define    TCP_CONN_NO_APP_REGISTERED                    0xFF3B
#define    TCP_CONN_FAILED_TO_SET_SOCKET                 0xFF3A
#define    TCP_CON_IP_SRC_DST_TUPLE_MISMATCH             0xFF39
#define    TCP_CONN_EXPECTED_APPLEN                      0xFF38
#define    TCP_APP_RESIZE_FAILED                         0xFF37
#define    TCP_L3_PROCESS_IP_FAILED                      0xFF36

/* l5 <=> tls */
#define    TLS_HMAC_CHECK_FAIL                           0xFF17
#define    TLS_READ_RECORD_TOO_BIG                       0xFF16
#define    TLS_CLIENTHELLO_MALFORMED                     0xFF15
#define    TLS_CLIENTHELLO_UNEXPECTED_MSG                0xFF14
#define    TLS_CLIENTHELLO_PARSE_ERROR                   0xFF13
#define    TLS_CLIENTHELLO_UNSUPPORTED_VER               0xFF12
#define    TLS_CLIENTHELLO_CURVE_NOMATCH                 0xFF11
#define    TLS_RESIZE_CLIENTHELLO_FAILED                 0xFF10
#define    TLS_CLIENT_TOO_MANY_SUITES                    0xFF0F
#define    TLS_CIPHSUITE_NOT_SUPPORTED                   0xFF0E
#define    TLS_EXTENSIONS_LEN_TOO_SMALL                  0xFF0D
#define    TLS_SERVHELLO_BAD_PREV_STATE                  0xFF0C
#define    TLS_SOCK_OPAQUE_SZ_TOO_SMALL                  0xFF0B
#define    TLS_CLIENT_KEYXCHG_UNEXPECTED_MSG             0xFF0A
#define    TLS_CLIENT_KEYXCHG_ECDH_MALFORMED             0xFF09
#define    TLS_CLIENT_KEYXCHG_EC_PT_COMPRESSED           0xFF08
#define    TLS_CLIENT_KEYXCHG_EC_PT_BADLEN               0xFF07
#define    TLS_INIT_EC_FAILED                            0xFF06
#define    TLS_ECDH_FAILED                               0xFF05
#define    TLS_FIN_BAD_STATE                             0xFF04
#define    TLS_FIN_DECRYPT_SZ                            0xFF03
#define    TLS_VERIFY_DATA_FAILED                        0xFF02
#define    TLS_FIN_TX_BAD_STATE                          0xFF01
#define    TLS_CLIENTHELLO_HASH_NOMEM                    0xFF00
#define    TLS_FIN_DECRYPT_FAILED                        0xFEFF
#define    TLS_WRITE_OVERFLOW                            0xFEFE
#define    TLS_WRITE_TYPE_OVERFLOW                       0xFEFD
#define    TLS_EXPECTED_APP_OR_ALERT                     0xFEFC
#define    TLS_APP_DATA_OF_ZERO_LEN                      0xFEFB
#define    TLS_DECRYPT_LEN_LT_ZERO                       0xFEFA
#define    TLS_MAX_RECS_EXCEEDED                         0xFEF9
/* crypto hash */
#define    SHA1_BUF_ERR                                  0xFEE9
#define    SHA1_FINAL_PAD_ERR                            0xFEE8
#define    SHA1_BUF_TOO_BIG                              0xFEE7
#define    SHA1_FINAL_COUNT_ERR                          0xFEE6
/* crypto ec */
#define    EC_INIT_NULL_PARAMS                           0xFED6
#define    EC_ERROR_NOMEM_INIT                           0xFED5
#define    EC_X2_FAILED                                  0xFED4
#define    EC_X2_x_3_FAILED                              0xFED3
#define    EC_NUMERATOR_ADD_FAILED                       0xFED2
#define    EC_YINV_FAILED                                0xFED1
#define    EC_S_x_YINV_FAILED                            0xFED0
#define    EC_MODP_FAILED                                0xFECF
#define    EC_X_x_X_MOD_P_FAILED                         0xFECE
#define    EC_Xr_PLUS_P_FAILED                           0xFECD
#define    EC_INIT_UNSUPPORTED_FORM                      0xFECC
#define    EC_INIT_Q_OVERFLOW                            0xFECB
#define    EC_INIT_CURVE_NOT_SUPPORTED                   0xFECA
#define    EC_SxYINV_MODP_FAILED                         0xFEC9
#define    EC_S2_MODP_FAILED                             0xFEC8
#define    EC_SUB_S2_2Xp_FAILED                          0xFEC7
#define    EC_Yr_MODP_FAILED                             0xFEC6
#define    EC_Yr_Xp_MINUS_Xr_x_S_FAILED                  0xFEC5
#define    EC_Xr_MODP_FAILED                             0xFEC4
#define    EC_Yr_SUB_FAILED                              0xFEC3
#define    EC_Yr_MUL_S_FAILED                            0xFEC2
#define    EC_Yr_MUL_Y_FAILED                            0xFEC1
#define    EC_Yr_ADD_Y_FAILED                            0xFEC0
#define    EC_PT_ADD_SUB_X_X1_ERR                        0xFEBF
#define    EC_PT_ADD_SUB_Y_Y1_ERR                        0xFEBE
#define    EC_PT_ADD_YINV_FAILED                         0xFEBD
#define    EC_PT_Yx_XINV_FAILED                          0xFEBC
#define    EC_PT_ADD_MODP_FAILED                         0xFEBB
#define    EC_PT_ADD_SxS_FAILED                          0xFEBA
#define    EC_PT_ADD_SSQ_MINUS_X_FAILED                  0xFEB9
#define    EC_PT_ADD_SSQ_MINUS_X1_FAILED                 0xFEB8
#define    EC_PT_ADD_XR_MODP_FAILED                      0xFEB7
#define    EC_PT_ADD_X_Xr_FAILED                         0xFEB6
#define    EC_PT_ADD_S_x_X_XR                            0xFEB5
#define    EC_PT_ADD_MODYr_FAILED                        0xFEB4
#define    EC_PT_ADD_SUB_Yp_FAILED                       0xFEB3
#define    EC_PT_kP_DBL_FAILED                           0xFEB2
#define    EC_PT_kP_ADD_FAILED                           0xFEB1
#define    EC_PT_ADD_SSQ_P_FAILED                        0xFEB0
#define    EC_X_X1_MODINV_FAILED                         0xFEAF
#define    EC_MODINV_2Yp_FAILED                          0xFEAE
#define    EC_S_INV_FAILED                               0xFEAD
#define    EC_Sinv_X_E_FAILED                            0xFEAC
#define    EC_Sinv_X_R_FAILED                            0xFEAB
#define    EC_U1_MOD_P_FAILED                            0xFEAA
#define    EC_SCALAR_MUL_FAILED                          0xFEA9
#define    EC_U2_MOD_P_FAILED                            0xFEA8
#define    EC_SCALAR_MUL1_FAILED                         0xFEA7
#define    EC_INIT_VARS_G_FAILED                         0xFEA6
#define    EC_INIT_VARS_Q_FAILED                         0xFEA5
#define    ECC_VERIFY_NOMEM                              0xFEA4
#define    EC_INIT_G_NOT_INITED                          0xFEA3
#define    EC_U1xG_PLUS_U2xQ_FAILED                      0xFEA2
#define    EC_Rs_MOD_N_FAILED                            0xFEA1
#define    EC_MOD_PARAM_CURVE_UNSUPPORTED                0xFEA0
#define    EC_SET_MOD_PARAM_P_U1_FAILED                  0xFE9F
#define    EC_SET_MOD_PARAM_N_U2_FAILED                  0xFE9E
#define    EC_SET_MOD_PARAM_P_U2_FAILED                  0xFE9D
#define    EC_SET_MOD_PARAM_N_R_FAILED                   0xFE9C
#define    EC_SIG_VERIFY_X_NEQ_R                         0xFE9B
#define    EC_GET_N_LEN_CURVE_UNSUPPORTED                0xFE9A
/* Error Codes bignum */
#define    HEXDUMP_ERR                                   0xFE8A
#define    ERR_ADD_NOT_ENOUGH_SPACE                      0xFE89
#define    ERR_SUB_NOT_ENOUGH_SPACE                      0xFE88
#define    ERR_MUL_NOT_ENOUGH_SPACE                      0xFE87
#define    WRN_MUL_NOT_ENOUGH_SPACE                      0xFE86
#define    WRN_SQR_NOT_ENOUGH_SPACE                      0xFE85
#define    DIVIDEND_ZERO                                 0xFE84
#define    DIVISOR_ZERO                                  0xFE83
#define    UNEXPECTED_NEG_REMAINDER                      0xFE82
#define    DIV_PAST_EXPECTED_ITERS                       0xFE81
#define    DIV_TMP_BUF_TOO_SMALL                         0xFE80
#define    DIVIDEND_LT_DIVISOR                           0xFE7F
#define    DIV_QUOTIENT_INDEX_LT_ZERO                    0xFE7E
#define    DIV_MUL_FAILED                                0xFE7D
#define    DIV_MOD_NO_MEM                                0xFE7C
#define    NO_MEM                                        0xFE7B
#define    MODEXP_MUL_FAILED                             0xFE7A
#define    MODEXP_DIV_FAILED                             0xFE79
#define    MODEXP_ARMODN_FAILED                          0xFE78
#define    MODEXP_ARMODN_SZ_TOO_BIG                      0xFE77
#define    MEMFIND_NULL_INPUT                            0xFE76
#define    MEMFIND_OFFSET_CALC_ERR                       0xFE75
#define    MEMFIND_DATA_NOT_FOUND                        0xFE74
#define    MODINV_RESULT_SZ_TOO_SMALL                    0xFE73
#define    MODINV_NOMEM                                  0xFE72
#define    MOD_BARRETT_NULL_PARAMS                       0xFE71
#define    MOD_BARRETT_MUL_Q0_MU_FAILED                  0xFE70
#define    MOD_BARRETT_MUL_Q_B_FAILED                    0xFE6F
#define    MOD_BARRETT_Q0_SZ_UNSUFFICIENT                0xFE6E
#define    QUOTIENT_OVERFLOW                             0xFE6D
#define    UNEXPECTED_MULTIPLIER                         0xFE6C
#define    MOD_BARRETT_A_GT_B_SQ                         0xFE6B
#define    MOD_BARRETT_INIT_NO_MEM                       0xFE6A
#define    MOD_BARRETT_SUB_A_Qo_FAILED                   0xFE69
#define    MOD_BARRETT_SUB_Qo_B_FAILED                   0xFE68
#define    MOD_BARRETT_SUB_Qo_B_ITERS                    0xFE67
#define    MINV_SUB_V_U_FAILED                           0xFE66
#define    MINV_SUB_U_V_FAILED                           0xFE65
#define    MINV_SUB_X2_X1_FAILED                         0xFE64
#define    MINV_SUB_X1_X2_FAILED                         0xFE63
#define    MINV_X2_ODD_ADD_FAILED                        0xFE62
#define    MINV_X1_ODD_ADD_FAILED                        0xFE61
#define    MINV_SUB_R_P_FAILED                           0xFE60
#define    MINV_SUB_R_P_ITERS                            0xFE5F
#define    MINV_CTZ_CALC_X_BUF_TOO_SMALL                 0xFE5E
#define    MINV_DOES_NOT_EXIST                           0xFE5D
#define    ADD_A_MUST_BE_SHORT_ALIGNED                   0xFE5C
#define    ADD_B_MUST_BE_SHORT_ALIGNED                   0xFE5B
#define    SUB_A_MUST_BE_SHORT_ALIGNED                   0xFE5A
#define    SUB_B_MUST_BE_SHORT_ALIGNED                   0xFE59
/* app layer */
#define    APP_HTTP_OUT_OF_MEMORY                        0xFE49
#define    APP_HTTP_SEND_RESPONSE                        0xFE48
/* asn.c do *not* shirk to add more */
#define    X690_0207_NULL_TAG                            0xFE38
#define    X690_0207_MAX_TAG_ERR                         0xFE37
#define    X690_0207_LEN_OCTETS_TOO_MANY                 0xFE36
#define    X690_0207_LEN_OCTETS_INDEFINITE               0xFE35
#define    X690_0207_OVERFLOW                            0xFE34
#define    X690_0207_PAYLOAD_OVERFLOW                    0xFE33
#define    X690_0207_NOREACH                             0xFE32
#define    ASN_TLV_TOO_BIG                               0xFE31
#define    ASN_CERT_CLASS_ERR                            0xFE30
#define    ASN_CERT_TYPE_ERR                             0xFE2F
#define    ASN_CERT_TAG_ERR                              0xFE2E
#define    ASN_CERT_TBSCERT_CLASS_ERR                    0xFE2D
#define    ASN_CERT_TBSCERT_TYPE_ERR                     0xFE2C
#define    ASN_CERT_TBSCERT_TAG_ERR                      0xFE2B
#define    ASN_CERT_VER_CLASS_ERR                        0xFE2A
#define    ASN_CERT_VER_TYPE_ERR                         0xFE29
#define    ASN_CERT_VER_TAG_ERR                          0xFE28
#define    ASN_CERT_VER_I_CLASS_ERR                      0xFE27
#define    ASN_CERT_VER_I_TYPE_ERR                       0xFE26
#define    ASN_CERT_VER_I_TAG_ERR                        0xFE25
#define    X690_0207_PAYLOAD_OVERFLOW_VERSION            0xFE24
#define    ASN_CERT_SER_CLASS_ERR                        0xFE23
#define    ASN_CERT_SER_TYPE_ERR                         0xFE22
#define    ASN_CERT_SER_TAG_ERR                          0xFE21
#define    X690_0207_PAYLOAD_OVERFLOW_SERIALNUM          0xFE20
#define    ASN_CERT_SIGALG_CLASS_ERR                     0xFE1F
#define    ASN_CERT_SIGALG_TYPE_ERR                      0xFE1E
#define    ASN_CERT_SIGALG_TAG_ERR                       0xFE1D
#define    ASN_CERT_SIGALG_OID_CLASS_ERR                 0xFE1C
#define    ASN_CERT_SIGALG_OID_TYPE_ERR                  0xFE1B
#define    ASN_CERT_SIGALG_OID_TAG_ERR                   0xFE1A
#define    ASN_CERT_SIGALG_NOT_SUPPORTED                 0xFE19
#define    X690_0207_PAYLOAD_OVERFLOW_SIGALG             0xFE18
#define    X690_0207_PAYLOAD_OVERFLOW_SIGALGP            0xFE17
#define    ASN_CERT_ISSUER_CLASS_ERR                     0xFE16
#define    ASN_CERT_ISSUER_TYPE_ERR                      0xFE15
#define    ASN_CERT_ISSUER_TAG_ERR                       0xFE14
#define    X690_0207_PAYLOAD_OVERFLOW_ISSUER             0xFE13
#define    ASN_CERT_VALID_CLASS_ERR                      0xFE12
#define    ASN_CERT_VALID_TYPE_ERR                       0xFE11
#define    ASN_CERT_VALID_TAG_ERR                        0xFE10
#define    ASN_CERT_VALIDFRM_CLASS_ERR                   0xFE0F
#define    ASN_CERT_VALIDFRM_TYPE_ERR                    0xFE0E
#define    ASN_CERT_VALIDFRM_TAG_ERR                     0xFE0D
#define    X690_0207_PAYLOAD_OVERFLOW_VALIDFRM           0xFE0C
#define    ASN_CERT_VALIDTO_CLASS_ERR                    0xFE0B
#define    ASN_CERT_VALIDTO_TYPE_ERR                     0xFE0A
#define    ASN_CERT_VALIDTO_TAG_ERR                      0xFE09
#define    X690_0207_PAYLOAD_OVERFLOW_VALIDTO            0xFE08
#define    ASN_CERT_SUBJECT_CLASS_ERR                    0xFE07
#define    ASN_CERT_SUBJECT_TYPE_ERR                     0xFE06
#define    ASN_CERT_SUBJECT_TAG_ERR                      0xFE05
#define    X690_0207_PAYLOAD_OVERFLOW_SUBJECT            0xFE04
#define    ASN_CERT_PUBK_CLASS_ERR                       0xFE03
#define    ASN_CERT_PUBK_TYPE_ERR                        0xFE02
#define    ASN_CERT_PUBK_TAG_ERR                         0xFE01
#define    ASN_CERT_PUBKALG_CLASS_ERR                    0xFE00
#define    ASN_CERT_PUBKALG_TYPE_ERR                     0xFDFF
#define    ASN_CERT_PUBKALG_TAG_ERR                      0xFDFE
#define    ASN_CERT_PUBKALG_OID_CLASS_ERR                0xFDFD
#define    ASN_CERT_PUBKALG_OID_TYPE_ERR                 0xFDFC
#define    ASN_CERT_PUBKALG_OID_TAG_ERR                  0xFDFB
#define    ASN_CERT_PUBKALG_NOT_SUPPORTED                0xFDFA
#define    X690_0207_PAYLOAD_OVERFLOW_PUBKALG            0xFDF9
#define    X690_0207_PAYLOAD_OVERFLOW_PUBKALGP           0xFDF8
#define    ASN_CERT_PUBK_VAL_CLASS_ERR                   0xFDF7
#define    ASN_CERT_PUBK_VAL_TYPE_ERR                    0xFDF6
#define    ASN_CERT_PUBK_VAL_TAG_ERR                     0xFDF5
#define    X690_0207_PAYLOAD_OVERFLOW_PUBKVAL            0xFDF4
#define    ASN_CERT_PUBK_PKEY_CLASS_ERR                  0xFDF3
#define    ASN_CERT_PUBK_PKEY_TYPE_ERR                   0xFDF2
#define    ASN_CERT_PUBK_PKEY_TAG_ERR                    0xFDF1
#define    X690_0207_PAYLOAD_OVERFLOW_PKEY               0xFDF0
#define    ASN_CERT_PUBK_RSAINTVAL_CLASS_ERR             0xFDEF
#define    ASN_CERT_PUBK_RSAINTVAL_TYPE_ERR              0xFDEE
#define    ASN_CERT_PUBK_RSAINTVAL_TAG_ERR               0xFDED
#define    X690_0207_PAYLOAD_OVERFLOW_RSAINTPUBKVAL      0xFDEC
#define    ASN_CERT_PUBK_RSAEXPVAL_CLASS_ERR             0xFDEB
#define    ASN_CERT_PUBK_RSAEXPVAL_TYPE_ERR              0xFDEA
#define    ASN_CERT_PUBK_RSAEXPVAL_TAG_ERR               0xFDE9
#define    X690_0207_PAYLOAD_OVERFLOW_RSAEXPVAL          0xFDE8
#define    ASN_CERT_EXTS_CLASS_ERR                       0xFDE7
#define    ASN_CERT_EXTS_TYPE_ERR                        0xFDE6
#define    ASN_CERT_EXTS_TAG_ERR                         0xFDE5
#define    ASN_CERT_EXT_CLASS_ERR                        0xFDE4
#define    ASN_CERT_EXT_TYPE_ERR                         0xFDE3
#define    ASN_CERT_EXT_TAG_ERR                          0xFDE2
#define    ASN_CERT_EXT_OID_CLASS_ERR                    0xFDE1
#define    ASN_CERT_EXT_OID_TYPE_ERR                     0xFDE0
#define    ASN_CERT_EXT_OID_TAG_ERR                      0xFDDF
#define    X690_0207_PAYLOAD_OVERFLOW_EXT_OID            0xFDDE
#define    ASN_CERT_EXT_NOT_SUPPORTED                    0xFDDD
#define    ASN_CERT_EXT_VAL_NOREACH                      0xFDDC
#define    X690_0207_PAYLOAD_OVERFLOW_EXT_KEYUSAGE       0xFDDB
#define    X690_0207_PAYLOAD_OVERFLOW_EXT_BASCONST       0xFDDA
#define    X690_0207_PAYLOAD_OVERFLOW_EXT_SUBJK_ID       0xFDD9
#define    X690_0207_PAYLOAD_OVERFLOW_EXT_CRLPTS         0xFDD8
#define    ASN_CERT_EXT_SUBKID_CLASS_ERR                 0xFDD7
#define    ASN_CERT_EXT_SUBKID_TYPE_ERR                  0xFDD6
#define    ASN_CERT_EXT_SUBKID_TAG_ERR                   0xFDD5
#define    X690_0207_PAYLOAD_OVERFLOW_EXT_SUBKID         0xFDD4
#define    ASN_CERT_TOO_MANY_ERRORS                      0xFDD3
#define    ASN_CERT_SIG_ALG_INCONSISTENT                 0xFDD2
#define    ASN_CERT_SIG_BLOCK_INVALID                    0xFDD1
#define    ASN_CERT_SIG_BLOCK_NO_MSG                     0xFDD0
#define    X690_0207_PAYLOAD_OVERFLOW_RSA_SIG_PARAM      0xFDCF
#define    ASN_CERT_SIG_RSASHA1_PAYLOAD_LEN_ERR          0xFDCE
#define    ASN_CERT_SIG_RSASHA1_VERIFY_FAILED            0xFDCD
#define    ASN_CERT_PUBKALG_ECDSA_CURVE_UNSUPORTED       0xFDCC
#define    ASN_CERT_PUBKALG_ECDSA_CURVE_SZ_ERROR         0xFDCB
#define    ASN_CERT_ECDSA_SIG_VAL_ERROR                  0xFDCA
#define    X690_0207_PAYLOAD_OVERFLOW_ECDSA_EXT          0xFDC9
#define    X690_0207_PAYLOAD_OVERFLOW_DSSSIG_S           0xFDC8

